services:
  db:
    image: postgres:17.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - db:/var/lib/postgresql/data
    networks:
      - budget-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image:
      adminer:5.4.1
    ports:
      - "8081:8080"
    networks:
      - budget-network
    depends_on:
      db:
        condition: service_healthy

  maildev:
    image: maildev/maildev:2.2.1
    ports:
      - "1080:1080"   # Web UI: http://localhost:1080
      - "1025:1025"   # SMTP
    # no auth/tls in dev; defaults are fine
    networks:
      - budget-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    depends_on:
      db:
        condition: service_healthy
    # ⬇️ Dev mode (no hostname requirement, HTTP allowed)
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

      # Use your local Postgres
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      #KC_DB_SCHEMA: keycloack

      # Optional: safe to keep; makes reverse proxies easier later
      KC_PROXY_HEADERS: xforwarded
    ports:
      - "8082:8080"   # admin console at http://localhost:8081
    #volumes:
    #- ./keycloak:/opt/keycloak/data/import:ro
    networks:
      - budget-network

volumes:
  db:

networks:
  budget-network:
    driver: bridge